### ISSUE TITLE
It will be better to support parse json in asynchronous?

### ISSUE THREAD

**Issue by Txiaozhe** [DremyGit/peg-json-parser#1]

**Comment by DremyGit** [comment]
This is only an example project for learning [PEG.js](https://github.com/pegjs/pegjs), not for production. Actually it could be replaced by `JSON.parse()`.

If you want to parse large json by asynchronous, maybe you can try some other library using streaming, such as [oboe.js](https://github.com/jimhigson/oboe.js), [JSONStream](https://github.com/dominictarr/JSONStream) etc...
